### ISSUE TITLE
The field/method selection box

### ISSUE THREAD

**Issue by Delors** [nicolas-mosch/java-bytecode-disassembler#1]
Hi,
I just found two issues:
1. the field/method selection box contains "signature" information.
2. no scrolling possibility is provided if the list of methods/fields is very long

![screen shot 2017-07-10 at 23 18 53](https://user-images.githubusercontent.com/329312/28040608-9c734932-65c6-11e7-9bff-4b809ee66ca2.png)

**Comment by romosch** [comment]
Hi,
2: will be fixed in next update
1: what information should be removed?

**Comment by Delors** [comment]
The details regarding the "Signature"
